### ISSUE TITLE
/root/go/pkg/mod/github.com/bitwormhole/wpm@v0.0.8/server/support/impldao/LocalRepositoryDaoImpl.go:113 record not found

### ISSUE THREAD

**Issue by wizardchao** [bitwormhole/wpm-app#1]
go run main.go报错 /root/go/pkg/mod/github.com/bitwormhole/wpm@v0.0.8/server/support/impldao/LocalRepositoryDaoImpl.go:113 record not found，请告知下原因

**Comment by bitwormhole** [comment]
数据库结构有冲突。建议更新到最新版本(v0.0.2)，并且配置使用 mysql 或者 sqlserver 作为数据源，以便定位更加准确的原因。数据源的配置请参考“src/main/resources/application-release.properties”这个文件里面的 "datasource.wpm.*" 部分
